Repository forrestguice/SuntimesWidget, pull requests merged in 2023-02, with the labels that each got.

#686 release 0.15.0
  CHANGELOG.md
  app/build.gradle
  fastlane/metadata/android/en-US/changelogs/97.txt
  fastlane/metadata/android/en-US/images/0.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/0.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/2.png
Labels: version-minor

#688 simplified/traditional Chinese translations & fixes
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: translation, zh_TW, zh_CN

#693 Norwegian (nb) translation update
  app/src/main/res/values-nb/strings.xml
Labels: translation, nb

#694 release 0.15.1
  CHANGELOG.md
  README.md
  app/build.gradle
  fastlane/metadata/android/en-US/changelogs/98.txt
Labels: version-patch

#698 Update strings.xml
  app/src/main/res/values-de/strings.xml
Labels: translation, de
