Repository forrestguice/SuntimesWidget, pull requests merged in 2024-01, with the labels that each got.

#756 release 0.15.10
  CHANGELOG.md
  README.md
  app/build.gradle
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-eo/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-eu/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
  fastlane/metadata/android/en-US/changelogs/107.txt
Labels: version-patch

#761 translations to Polish and Esperanto
  app/src/main/res/values-eo/strings.xml
  app/src/main/res/values-pl/strings.xml
Labels: translation, pl, eo

#765 feat: updated Chinese translations
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: translation, zh_TW, zh_CN
