Repository forrestguice/SuntimesWidget, pull requests merged in 2024-11, with the labels that each got.

#839 Chinese Translations updates
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: translation, zh_TW, zh_CN

#840 Release 0.16.3
  CHANGELOG.md
  app/build.gradle
  fastlane/metadata/android/en-US/changelogs/117.txt
Labels: version-patch

#841 updated translations to Polish and Esperanto
  app/src/main/res/values-eo/strings.xml
  app/src/main/res/values-pl/strings.xml
Labels: translation, pl, eo

#851 remove jitpack.io from build
  app/build.gradle
  app/src/main/java/ca/rmen/sunrisesunset/SunriseSunset.java
  app/src/main/java/com/luckycatlabs/sunrisesunset/SunriseSunsetCalculator.java
  app/src/main/java/com/luckycatlabs/sunrisesunset/Zenith.java
  app/src/main/java/com/luckycatlabs/sunrisesunset/calculator/SolarEventCalculator.java
  app/src/main/java/com/luckycatlabs/sunrisesunset/dto/Location.java
  build.gradle
  lib-quadflask-colorpicker/.gitignore
  lib-quadflask-colorpicker/README.md
  lib-quadflask-colorpicker/build.gradle
  lib-quadflask-colorpicker/proguard-rules.pro
  lib-quadflask-colorpicker/src/androidTest/java/com/flask/colorpicker/ApplicationTest.java
  lib-quadflask-colorpicker/src/main/AndroidManifest.xml
  lib-quadflask-colorpicker/src/main/java/com/flask/colorpicker/CircleColorDrawable.java
  lib-quadflask-colorpicker/src/main/java/com/flask/colorpicker/ColorCircle.java
  lib-quadflask-colorpicker/src/main/java/com/flask/colorpicker/ColorPickerPreference.java
  lib-quadflask-colorpicker/src/main/java/com/flask/colorpicker/ColorPickerView.java
  lib-quadflask-colorpicker/src/main/java/com/flask/colorpicker/OnColorChangedListener.java
  lib-quadflask-colorpicker/src/main/java/com/flask/colorpicker/OnColorSelectedListener.java
  lib-quadflask-colorpicker/src/main/java/com/flask/colorpicker/Utils.java
  lib-quadflask-colorpicker/src/main/java/com/flask/colorpicker/builder/ColorPickerClickListener.java
  lib-quadflask-colorpicker/src/main/java/com/flask/colorpicker/builder/ColorPickerDialogBuilder.java
  lib-quadflask-colorpicker/src/main/java/com/flask/colorpicker/builder/ColorWheelRendererBuilder.java
  lib-quadflask-colorpicker/src/main/java/com/flask/colorpicker/builder/PaintBuilder.java
  lib-quadflask-colorpicker/src/main/java/com/flask/colorpicker/renderer/AbsColorWheelRenderer.java
  lib-quadflask-colorpicker/src/main/java/com/flask/colorpicker/renderer/ColorWheelRenderOption.java
  lib-quadflask-colorpicker/src/main/java/com/flask/colorpicker/renderer/ColorWheelRenderer.java
  lib-quadflask-colorpicker/src/main/java/com/flask/colorpicker/renderer/FlowerColorWheelRenderer.java
  lib-quadflask-colorpicker/src/main/java/com/flask/colorpicker/renderer/SimpleColorWheelRenderer.java
  lib-quadflask-colorpicker/src/main/java/com/flask/colorpicker/slider/AbsCustomSlider.java
  lib-quadflask-colorpicker/src/main/java/com/flask/colorpicker/slider/AlphaSlider.java
  lib-quadflask-colorpicker/src/main/java/com/flask/colorpicker/slider/LightnessSlider.java
  lib-quadflask-colorpicker/src/main/java/com/flask/colorpicker/slider/OnValueChangedListener.java
  lib-quadflask-colorpicker/src/main/res/layout/color_preview.xml
  lib-quadflask-colorpicker/src/main/res/layout/color_selector.xml
  lib-quadflask-colorpicker/src/main/res/layout/color_widget.xml
  lib-quadflask-colorpicker/src/main/res/layout/picker_edit.xml
  lib-quadflask-colorpicker/src/main/res/values/attrs.xml
  lib-quadflask-colorpicker/src/main/res/values/dimens.xml
  lib-quadflask-colorpicker/src/main/res/values/styles.xml
  settings.gradle
Labels: build
