Repository forrestguice/SuntimesWidget, pull requests merged in 2024-02, with the labels that each got.

#769 updated translations to Polish and Esperanto
  app/src/main/res/values-eo/strings.xml
  app/src/main/res/values-pl/strings.xml
Labels: translation, pl, eo

#764 CalculatorProvider
  app/src/main/java/com/forrestguice/suntimeswidget/calculator/CalculatorProvider.java
  app/src/main/java/com/forrestguice/suntimeswidget/calculator/core/CalculatorProviderContract.java
Labels: enhancement

#775 added translations to Russian
  app/src/main/res/values-ru/strings.xml
Labels: translation, ru
