Repository forrestguice/SuntimesWidget, pull requests merged in 2024-09, with the labels that each got.

#832 Norwegian (nb) translation update
  app/src/main/res/values-nb/strings.xml
Labels: translation, nb

#833 translations to Polish and Esperanto
  app/src/main/res/values-eo/strings.xml
  app/src/main/res/values-pl/strings.xml
Labels: translation, pl, eo

#836 Chinese (zh) translations
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: translation, zh_TW, zh_CN

#829 release 0.16.2
  CHANGELOG.md
  app/build.gradle
  fastlane/metadata/android/en-US/changelogs/116.txt
Labels: version-patch
