Repository forrestguice/SuntimesWidget, pull requests merged in 2024-04, with the labels that each got.

#786 Add Arabic translation
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-eo/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-eu/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
Labels: translation, ar

#789 places
  app/src/androidTest/java/com/forrestguice/suntimeswidget/SuntimesResTest.java
  app/src/main/java/com/forrestguice/suntimeswidget/WelcomeActivity.java
  app/src/main/java/com/forrestguice/suntimeswidget/getfix/BuildPlacesTask.java
  app/src/main/java/com/forrestguice/suntimeswidget/getfix/PlacesListFragment.java
  app/src/main/java/com/forrestguice/suntimeswidget/settings/fragments/PlacesPrefsFragment.java
  app/src/main/res/values/places.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/forrestguice/suntimeswidget/getfix/BuildPlacesTaskTest0.java
Labels: enhancement

#788 Locale Translation (Chinese)
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: translation, zh_TW, zh_CN

#787 release 0.15.14
  CHANGELOG.md
  README.md
  app/build.gradle
  fastlane/metadata/android/en-US/changelogs/111.txt
Labels: version-patch

#791 Chinese translation completions & trimming trailing additional character
  CONTRIBUTING.md
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: translation, zh_TW, zh_CN
