Repository forrestguice/SuntimesWidget, pull requests merged in 2024-08, with the labels that each got.

#811 release 0.16.0
  CHANGELOG.md
  app/build.gradle
  fastlane/metadata/android/en-US/changelogs/114.txt
Labels: version-minor

#813 Chinese translation
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: translation, zh_TW, zh_CN

#817 Norwegian (nb) translation update
  app/src/main/res/values-nb/strings.xml
Labels: translation, nb

#819 Updating pt_BR translation
  app/src/main/res/values-pt-rBR/strings.xml
Labels: translation, pt_BR

#824 translations to Polish and Esperanto
  app/src/main/res/values-eo/strings.xml
  app/src/main/res/values-pl/strings.xml
Labels: translation, pl, eo

#821 release 0.16.1
  CHANGELOG.md
  app/build.gradle
  fastlane/metadata/android/en-US/changelogs/115.txt
Labels: version-patch
