Repository forrestguice/SuntimesWidget, pull requests merged in 2025-09, with the labels that each got.

#897 crash report notification
  app/src/androidTest/java/com/forrestguice/suntimeswidget/ExceptionActivityTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/forrestguice/suntimeswidget/ExceptionActivity.java
  app/src/main/java/com/forrestguice/suntimeswidget/ExceptionHandler.java
  app/src/main/java/com/forrestguice/suntimeswidget/ExceptionNotification.java
  app/src/main/java/com/forrestguice/suntimeswidget/SuntimesApplication.java
  app/src/main/res/layout/layout_activity_exception.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#896 release 0.16.10
  CHANGELOG.md
  app/build.gradle
  fastlane/metadata/android/en-US/changelogs/124.txt
Labels: version-patch

#899 Norwegian (nb) translation update
  app/src/main/res/values-nb/strings.xml
Labels: translation, nb
